apiVersion: apps/v1
kind: Deployment
metadata:
  name: gs-algorithm
spec:
  selector:
    matchLabels:
      app: gs-algorithm
  template:
    metadata:
      labels:
        app: gs-algorithm
    spec:
      serviceAccountName: scaler-service-account
      containers:
        - name: gs-algorithm
          image: lorenzobacchiani/teastore_gs
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: INCLUSTER_CONFIG
              value: "true"
            - name: K_BIG
              value: "10"
            - name: SLEEP
              value: "20"
            - name: K
              value: "8"
            - name: ERROR_LIMIT
              value: "3"
            - name: PROACTIVE
              value: "false"
            - name: PROACTIVE_REACTIVE
              value: "false"
            - name: PROMETHEUS_SERVICE_ADDRESS
              value: "prometheus-service.monitoring.svc.cluster.local"
            - name: PROMETHEUS_SERVICE_PORT
              value: "8080"
            - name: MONITOR_ONLY
              value: "false"
            - name: FOLDER_PATH
              value: "/app/my_files"
            - name: SYSTEM_BASE_CONFIGURATION
              value: 1,1,1,1,2
            - name: MICROSERVICES_MCL
              value: 150,905,190,5000,600
            - name: MICROSERVICES_MF
              value: "1,4,1,3,6"
            - name: INCREMENT_1
              value: "2,1,1,0,2"
            - name: INCREMENT_2
              value: "1,1,1,0,2"
            - name: HTTP_REQUESTS_METRIC
              value: "http_requests_total_webUI_counter"              
            - name: BEHAVIOUR_EXECUTION_METRIC
              value: "behaviour_execution"
            - name: BEHAVIOUR_TIME_METRIC
              value: "behaviour_time_execution"
            - name: MESSAGE_LOST_METRIC
              value: "message_lost_webUI"
            - name: ADDITIONAL_SERVICE
              value: "0"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gs-algorithm-service
spec:
  selector:
    app: gs-algorithm
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000