apiVersion: v1
kind: Pod
type: auth-type
spec:
  containers:
    - name: auth
      image: giovaz94/tea-store-general
      imagePullPolicy: Always
      ports:
        - containerPort: 8002
      resources:
        requests:
          cpu: "10m"
          memory: "10M"
      env:
        - name: MCL
          value: "190"
        - name: SERVICE_NAME
          value: "auth"
        - name: PORT
          value: "80"
        - name: MAX_SIZE
          value: "1000"
        - name: OUTPUT_SERVICES
          value: '{"http://persistence-service/request":"1"}'
        - name: MAX_CONNECTIONS
          value: "70"
        - name: PIPELINE_COUNT
          value: "1"
          
  restartPolicy: Always

ports:
  strong:
    - type: "persistence-service-type"
      config:
        envName: PORT_PERSISTENCE_SERVICE
        containers :
          - name : "auth"