apiVersion: v1
kind: Pod
type: image-type
spec:
  containers:
    - name: image
      image: giovaz94/tea-store-general
      imagePullPolicy: Always
      ports:
        - containerPort: 8002
      resources:
        requests:
          cpu: "10m"
          memory: "10M"
      env:
        - name: MCL
          value: "600"
        - name: SERVICE_NAME
          value: "image"
        - name: MAX_SIZE
          value: "1000"
        - name: PORT
          value: "80"
        - name: OUTPUT_SERVICES
          value: '{}'
        - name: MAX_CONNECTIONS
          value: "70"
        - name: PIPELINE_COUNT
          value: "1"
  restartPolicy: Always
