apiVersion: v1
kind: Pod
type: persistence-type    
spec:
  containers:
    - name: persistence
      image: giovaz94/tea-store-general
      imagePullPolicy: Always
      ports:
        - containerPort: 8003
      resources:
        requests:
          cpu: "10m"
          memory: "10M"
      env:
        - name: MCL
          value: "905"
        - name: SERVICE_NAME
          value: "persistence"
        - name: PORT
          value: "80"
        - name: MAX_SIZE
          value: "1000"
        - name: OUTPUT_SERVICES
          value: '{}'
        - name: MAX_CONNECTIONS
          value: "70"
        - name: PIPELINE_COUNT
          value: "1"
  restartPolicy: Always
