apiVersion: v1
kind: Pod
type: webui-type
spec:
  containers:
    - name: webui
      image: giovaz94/tea-store-general
      imagePullPolicy: Always
      ports:
        - containerPort: 8001
      resources:
        requests:
          cpu: "10m"
          memory: "10M"
      env:
          - name: MCL
            value: "150"
          - name: SERVICE_NAME
            value: "webUI"
          - name: PORT
            value: "80"
          - name: MAX_SIZE
            value: "1000"
          - name: OUTPUT_SERVICES
            value: '{"http://persistence-service/request":"1", "http://recommender-service/request":"1", "http://image-service/request":"2"}'
          - name: MAX_CONNECTIONS
            value: "70"
          - name: PIPELINE_COUNT
            value: "1"
       
  restartPolicy: Always

ports:
  strong:
    - type: "image-service-type"
      config:
        envName: PORT_IMAGE_SERVICE
        containers :
          - name : "webui"
    - type: "persistence-service-type"
      config:
        envName: PORT_PERSISTENCE_SERVICE
        containers :
          - name : "webui"
    - type: "auth-service-type"
      config:
        envName: PORT_AUTH_SERVICE
        containers :
          - name : "webui"
    - type: "recommender-service-type"
      config:
        envName: PORT_RECOMMENDER_SERVICE
        containers :
          - name : "webui"
    - type: "prometheus-service-type"
      config:
        envName: PORT_PROMETHEUS_SERVICE
        containers :
          - name : "webui"

